name: AdvanceShopGUI
api: [4.0.0]
main: ShopGUI\XenialXerus\main
version: 1.0.0
author: XenialXerus
dependency: Capital
description: "Open Shop GUI For Ur Server"

commands:
  shopgui:
    description: "Permission For Shop Gui"
    usage: "/shopgui"
    permission: shop.use.cmd

permissions:
  shop.use.cmd:
    default: true



